# Generated by Django 2.2.7 on 2021-08-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_pergunta_data_encerramento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Rótulo',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['texto'], 'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='autor',
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nome', models.CharField(max_length=80)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enquetes.Perfil')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='rotulos',
            field=models.ManyToManyField(to='enquetes.Rotulo'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enquetes.Autor'),
        ),
    ]
