# Generated by Django 2.2.7 on 2021-08-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0005_auto_20210818_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
