# Generated by Django 2.2.7 on 2021-08-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0006_auto_20210818_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotulo',
            options={'ordering': ['titulo'], 'verbose_name': 'Rótulo', 'verbose_name_plural': 'Rótulos'},
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enquetes.Perfil')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enquetes.Autor'),
        ),
    ]
