# Generated by Django 2.2.7 on 2021-08-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0007_auto_20210818_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='perfil',
        ),
    ]
